[package]
name = "hellorust"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"


[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]
