name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: target/release/libhellorust.so
            asset_name: libhellorust.so(x86_64)
          # - name: macos
          #   os: macos-latest
          #   target: x86_64-apple-darwin
          #   artifact_name: target/release/libhellorust.dylib
          #   asset_name: libhellorust.dylib(x86_64)
          - name: linux-arm
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: target/release/libhellorust.so
            asset_name: libhellorust.so(aarch64)
            linker: gcc-aarch64-linux-gnu
            cross: true
          # - name: macos-arm
          #   os: macos-latest
          #   target: aarch64-apple-darwin
          #   artifact_name: target/release/libhellorust.dylib
          #   asset_name: libhellorust.dylib(aarch64)

    steps:
    - name: Install Linker
      if: matrix.cross
      run: |
        sudo apt update
        sudo apt install ${{ matrix.linker }}

    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        target: ${{ matrix.target }}
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked --target ${{ matrix.target }}

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}