name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: macos
            os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: target/x86_64-apple-darwin/release/libhellorust.dylib
            asset_name: libhellorust.dylib
            platform: platforms/hellorust-darwin-x64
            cross: false
          - name: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: target/x86_64-unknown-linux-gnu/release/libhellorust.so
            asset_name: libhellorust.so
            platform: platforms/hellorust-linux-x64
            cross: false
          - name: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: target/aarch64-unknown-linux-gnu/release/libhellorust.so
            asset_name: libhellorust.so(aarch64)
            platform: platforms/hellorust-linux-arm64
            cross: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: ${{ matrix.cross }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --target ${{ matrix.target }} --release

      - name: Npm Publish
        uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NPM_TOKEN: ${{ secrets.NPM_PUBLIST_TOKEN }}
      - run: pwd
      - run: |
          cp ${{ matrix.artifact_name }} ${{ matrix.platform }}/index.node
          cd ${{ matrix.platform }}
          ls
          npm publish --access public
      - run: pwd
      - run: npm publish --access public

      # - name: Upload binaries to release
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.asset_name }}
      #     path: ${{ matrix.artifact_name }}

      # - name: ls
      #   run: |
      #     echo hellotarget
      #     ls target

      # - name: Upload binaries to release
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: target/aarch64-unknown-linux-gnu/release/libhellorust.so
      #     name: libhellorust.so(aarch64)


  # publish:
  #   name: Publish for ${{ matrix.name }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       include:
  #         # - name: linux
  #         #   os: ubuntu-latest
  #         #   target: x86_64-unknown-linux-gnu
  #         #   artifact_name: target/release/libhellorust.so
  #         #   asset_name: libhellorust.so(x86_64)
  #         - name: linux-arm
  #           os: ubuntu-latest
  #           # target: aarch64-unknown-linux-musl
  #           target: armv7-unknown-linux-gnueabihf
  #           artifact_name: target/release/libhellorust.so
  #           asset_name: libhellorust.so(aarch64)
  #           cross: true

  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       target: ${{ matrix.target }}
  #       profile: minimal
  #       toolchain: stable

  #   - name: Build
  #     # run: cargo build --release --locked --target ${{ matrix.target }}
  #     run: |
  #       apt install gcc-arm-linux-gnueabihf
  #       cargo rustc --target ${{ matrix.target }}

  #   - name: Upload binaries to release
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: ${{ matrix.asset_name }}
  #       path: ${{ matrix.artifact_name }}